import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./Components/Header";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata = {
   title: "YESCA",
   description: "Generated by create next app",
   icons: {
      icon: "/images/YESCA.svg",
   },
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Header />
            {children}
         </body>
      </html>
   );
}
