"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./Components/Header";
import { useEffect, useRef } from "react";
import gsap from "gsap";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

// export const metadata = {
//    title: "YESCA",
//    description: "Generated by create next app",
//    icons: {
//       icon: "/images/YESCA.svg",
//    },
// };

export default function RootLayout({ children }) {
   const leftDoor = useRef();
   const rightDoor = useRef();

   const Y = useRef();
   const Dot = useRef();

   useEffect(() => {
      // Example animation: doors close, then open

      const tl = gsap.timeline({ defaults: { ease: "power2.inOut", duration: 1 } });

      // Doors initially open

      // Close doors from the sides
      tl.fromTo(leftDoor.current, { x: "-130%" }, { x: "0%" }, 0)
         .fromTo(rightDoor.current, { x: "100%" }, { x: "0%" }, 0)

         // Small pause
         .to({}, { duration: 0.4 })

         // Open doors again
         .to(leftDoor.current, { x: "-130%" }, "open")
         .to(rightDoor.current, { x: "100%" }, "open");
   }, []);

   return (
      <html lang="en">
         <title>yesca.in</title>
         <link rel="icon" type="image/favicon" href="/images/YESCA.svg" />
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Header />
            {/* Door panels */}

            <div ref={leftDoor} className="door left hidden md:flex">
               <img ref={Y} src="/LattersSvg/Y.svg" alt="Y" className="left-door-img" />
            </div>

            <div ref={rightDoor} className="door right hidden md:flex">
               <img ref={Dot} src="/LattersSvg/Dot.svg" alt="Dot" className="right-door-img" />
            </div>
            {children}
         </body>
      </html>
   );
}
